### ISSUE TITLE
Create AppVeyor build and publish to IntelliTect MyGet feed.

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/AspNetCore.TestHost.WindowsAuth#3]

**Comment by ascott18** [comment]
@kamonson or whoever ends up taking this:

- We should version the package with the same major/minor as our dependencies (e.g. the current code base targets AspNetCore 2.0.0, so we should version as 2.0.0).
- The aspnetcore dependencies should be bumped to `2.1.<latest>`
- The build should run the tests in IntelliTect.AspNetCore.TestHost.WindowsAuth.Test
- The build doesn't need to do anything with the .Example project.
- IntelliTect.AspNetCore.TestHost.WindowsAuth is the one that should be packaged and pushed to nuget.
